repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Replace with the latest version
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: check-yaml  # Validates YAML syntax
      - id: check-json  # Validates JSON syntax
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Replace with the latest version
    hooks:
      - id: black  # Formats Python code
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Replace with the latest version
    hooks:
      - id: flake8  # Linter for Python
        args: [--max-line-length=88]  # Match Black's line length
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Replace with the latest version
    hooks:
      - id: mypy  # Type checker for Python
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1  # Replace with the latest version
    hooks:
      - id: pyupgrade  # Automatically upgrades Python syntax
        args: [--py39-plus]  # Target Python 3.9+
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.2  # Replace with the latest version
    hooks:
      - id: ruff  # Fast Python linter
        args: ["--fix"]  # Automatically fix lint issues
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Replace with the latest version
    hooks:
      - id: isort  # Organizes imports
